apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: goreplay-daemon
spec:
  selector:
    matchLabels:
      name: goreplay-daemon
  template:
    metadata:
      labels:
        name: goreplay-daemon
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet # For replaying to local dns eg. --output-http http://nginx-service.goreplay.svc.cluster.local:80
      serviceAccountName: goreplay
      containers:
      - name: goreplay
        imagePullPolicy: Always
        image: buger/goreplay:2.0.0-rc2
        command:
          - "--input-raw k8s://deployments/nginx:80"
          - "--output-stdout"
